### ISSUE TITLE
Don't work standard cordova plugins with this plugin

### ISSUE THREAD

**Issue by ryzhkin** [ludei/webview-plus-ios#3]
I do this:
cordova platform add ios
cocoonjs plugin add com.ludei.ios.webview.plus -d
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.device-motion
cordova plugin add org.apache.cordova.network-information
cordova plugin add com.hutchind.cordova.plugins.streamingmedia
cordova build ios

Application works but doesn't work cordova plugins: org.apache.cordova.device-motion, com.hutchind.cordova.plugins.streamingmedia and etc.

**Comment by allenzhaoxin** [comment]
I have some issues,  when add camera plugin.

**Comment by nitzanwilnai** [comment]
It appears that mixing WebView+ and PhoneGap plugins is not supported: http://support.ludei.com/hc/communities/public/questions/201575145-iOS-PhoneGap-Plugins-not-loading-after-adding-CocoonJs-plugin

**Comment by keianhzo** [comment]
As stated in the Readme, this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features.

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
