### ISSUE TITLE
Pink background

### ISSUE THREAD

**Issue by kenvunz** [ludei/webview-plus-ios#4]
Hi,

After installed the plugin to my existing cordova project, it seems to work fine, but there is a pink background overlay on top. Is this expected behaviour? Also, is there anyway to change the pink background to something else, like black?

Cheers
Ken

**Comment by keianhzo** [comment]
As stated in the Readme, this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features.

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
