### ISSUE TITLE
Manually Installation Documenation

### ISSUE THREAD

**Issue by ndevr** [ludei/webview-plus-ios#6]
Hey it would be cool if you can write down a documentation for the manually installation. We are looking forward to see it in other projects like meteor.

**Comment by keianhzo** [comment]
As stated in the Readme, this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features.

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
