### ISSUE TITLE
Not compatible with Cordova 4.2.0

### ISSUE THREAD

**Issue by atom2ueki** [ludei/webview-plus-ios#7]
`cocoonjs plugin add com.ludei.ios.webview.plus`

Error: Error: This plugin should be installed using cordova 4.0.0 or below. Your cordova version is 4.2.0

**Comment by LibelulaV** [comment]
Today we released the new Cocoon Beta. It is based on Cordova. 

http://cocoon.io/

Here you can find more information: https://blog.cocoon.io/cocoon-beta/

There is a new and full up to date Webview+. 

Regards

**Comment by keianhzo** [comment]
As stated in the Readme, this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features.

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
