### ISSUE TITLE
DisallowOverscroll not working

### ISSUE THREAD

**Issue by atom2ueki** [ludei/webview-plus-ios#8]
I want to disable the scroll of the webview plus, but put the below code into config.xml not working for webview plus
<preference name="DisallowOverscroll" value="true"/>

**Comment by LibelulaV** [comment]
Hello, 

We are working on a new cloud compiler based on cordova and and up to date webview+ plugin. 
You can request an invitation here: https://cocoon.io/
In the new cloud you can edit the config.xml directly at the cloud and you will receive all the error logs to your email. 
If you want more information, here there is a blog post about it: https://blog.cocoon.io/cocoon-beta/

Cheers

**Comment by keianhzo** [comment]
As stated in the Readme, this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features.

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
