### ISSUE TITLE
webview-plus-ios  - 2 errors Xcode. can't build the game 

### ISSUE THREAD

**Issue by san40511** [ludei/webview-plus-ios#9]
ld: '/Users/alexnaberezhnev/Projects/Alien_Trip/platforms/ios/Alien trip/Plugins/com.ludei.ios.webview.plus/Release-iphoneos-libCocoonJS_force_load.a(IOSCocoonJSView.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

d: '/Users/alexnaberezhnev/Projects/Alien_Trip/platforms/ios/Alien trip/Plugins/com.ludei.ios.webview.plus/Release-iphoneos-libCocoonJS_force_load.a(IOSCocoonJSView.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

**Comment by keianhzo** [comment]
Hello,

As stated in the [Readme](https://github.com/ludei/webview-plus-ios/blob/master/README.md), this project has been discontinued in favor of the new http://cocoon.io cloud so we are not currently giving any support to it. The new cocoon.io has support for the latest and most updated iOS Webview+ and also tons of new features. 

It's free and you can create a new account easily at: https://cloud.cocoon.io/signup/
